import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PlanetProvider } from "./contexts/planetContext";
import StyledComponentsRegistry from "./contexts/registry";
import { LoadingProvider } from "./contexts/loadingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <LoadingProvider>
            <PlanetProvider>{children}</PlanetProvider>
          </LoadingProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
